### ISSUE TITLE
"Error decoding PUT body" when using APIWrapper's put function

### ISSUE THREAD

**Issue by pandaxtc** [PumPum7/Tatsu.py#1]
Any functions that use `put` result in this message: 

```
{"message":"Error decoding PUT body. Error: 696e76616c69642063686172616374657220276127206c6f6f6b696e6720666f7220626567696e6e696e67206f662076616c7565"}
```

A possible fix for this is changing the kwarg here from `data` to `json`:
https://github.com/PumPum7/Tatsumaki.py/blob/02ae7eabe3505dab6bb0810eca4889659ee76878/wrapper.py#L27

**Comment by PumPum7** [comment]
will be fixed in the next update (which will happen today)
